// frontend/webApps/chatapp/resources/oda-native-client-sdk-js-24.06/samples/angular/src/app/card/card.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  standalone: true,
  selector: 'app-card',
  templateUrl: './card.component.html',
  styleUrls: ['./card.component.css'],
  imports: [CommonModule]
})
export class CardComponent implements OnInit {

  @Input() messagePayload: any;
  @Output() cardEvent = new EventEmitter<any>();

  constructor() { }

  ngOnInit(): void {
  }

  onActionClick(action: any) {
    this.cardEvent.emit(action);
  }

}

<div *ngIf="messagePayload">
  <div class="card">
    <div class="header">This is a Angular Component</div>
    <ul>
      <li class="card-item" *ngFor="let card of messagePayload.cards">
        <div class="card-info">
          <img class="card-image" [src]="card.imageUrl" alt="Card" />
          <div class="info">
            <div class="title">{{card.title}}</div>
            <div class="actions">
              <button *ngFor="let action of card.actions" (click)="onActionClick(action)">{{action.label}}</button>
            </div>
          </div>
        </div>
      </li>
    </ul>
  </div>
  <div class="actions-wrapper" *ngIf="messagePayload.actions && messagePayload.actions.length">
    <button *ngFor="let action of messagePayload.actions" (click)="onActionClick(action)">{{action.label}}</button>
  </div>
</div>

// frontend/webApps/chatapp/resources/oda-native-client-sdk-js-24.06/samples/react/src/Card.js
import './Card.css';

function Card(props) {
    function handleAction(action) {
        if (props.onAction) {
            props.onAction(action);
        }
    }

    return <div className="card">
        <ul>
            <div className="header">This is a React component</div>
            {props.cards.map((card, index) =>
                <li className="card-item" key={index}>
                    <div className='card-info'>
                        <img className='card-image' src={card.imageUrl} alt="Card"></img>
                        <div className='info'>
                            <div className='title'>{card.title}</div>
                            <div className='actions'>
                                {card.actions.map((action, index) =>
                                    <button key={index} onClick={(e) => handleAction(action, e)}>{action.label}</button>
                                )}
                            </div>
                        </div>
                    </div>
                </li>
            )}
        </ul>
    </div>;
}

export default Card;
